// <auto-generated />
using System;
using FINAL_WEB_JERONIMO_DUQUE_RUIZ.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FINAL_WEB_JERONIMO_DUQUE_RUIZ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525145358_SegundaMigracionEstructuraCompleta")]
    partial class SegundaMigracionEstructuraCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FINAL_WEB_JERONIMO_DUQUE_RUIZ.Models.Preguntas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Enunciado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("FINAL_WEB_JERONIMO_DUQUE_RUIZ.Models.Respuesta", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("enunciado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("pregunta_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("pregunta_Id");

                    b.ToTable("Respuesta");
                });

            modelBuilder.Entity("FINAL_WEB_JERONIMO_DUQUE_RUIZ.Models.Respuesta", b =>
                {
                    b.HasOne("FINAL_WEB_JERONIMO_DUQUE_RUIZ.Models.Preguntas", "pregunta")
                        .WithMany()
                        .HasForeignKey("pregunta_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pregunta");
                });
#pragma warning restore 612, 618
        }
    }
}
